model:
  name: Attention_SAC
  remarks: MAX speed set to 10m/s
  reward_func: dense
  include_context: True

action_adapter:
  max_speed: 10

PPO: 
  batch_size: 128
  n_steps: 6144
  learning_rate: 7.5e-5
  ent_coef: 0.01
  target_kl: 0.05
  seed: 1

SAC:
  batch_size: 64
  buffer_size: 1000000
  ent_coef: "auto"
  ent_scheduler: false
  learning_starts: 5000
  lr: 0.0003
  seed: 1

env:
  num_envs: 6
  scenario: [10]

train:
  timesteps: 50688
  num_epochs: 60
  seed: 1   #env seed (model seeds overwrites this if provided)
  device: 'cuda:0'

eval:
  episodes: 50
  num_envs: 1
  eval_seed: 1