gpu: 5 #any identifier for your device (useful when using multiple devices)

scenario: 10
eval_eps: 50    #eval episodes per seed
num_seeds: 5
pred_mode: deterministic

model_name: Attention_SAC
safety_mode: False
remarks: "best checkpoint, modified waypoints"

## recommended to provide absolute path
model_path: "-"
checkpoint: 0   #number of timesteps the model is trained for

context: True
reward_func: "dense"
interface_version: 4
max_speed: 10